# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: matchmaker.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10matchmaker.proto\"2\n\x0eNewGameRequest\x12\x0e\n\x06gameId\x18\x01 \x01(\t\x12\x10\n\x08playerId\x18\x02 \x01(\t\"\x1f\n\x0cNewGameReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x11\n\x0fListGameRequest\"B\n\rListGameReply\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0e\n\x06gameId\x18\x02 \x01(\t\x12\x10\n\x08playerId\x18\x03 \x01(\t\"3\n\x0f\x46indGameRequest\x12\x0e\n\x06gameId\x18\x01 \x01(\t\x12\x10\n\x08playerId\x18\x02 \x01(\t\"B\n\rFindGameReply\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0e\n\x06gameId\x18\x02 \x01(\t\x12\x10\n\x08playerId\x18\x03 \x01(\t\"5\n\x11\x44\x65leteGameRequest\x12\x0e\n\x06gameId\x18\x01 \x01(\t\x12\x10\n\x08playerId\x18\x02 \x01(\t\"\"\n\x0f\x44\x65leteGameReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x11\n\x0fSaveGameRequest\" \n\rSaveGameReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\"#\n\x11ListPlayerRequest\x12\x0e\n\x06gameId\x18\x01 \x01(\t\"%\n\x0fListPlayerReply\x12\x12\n\nplayerList\x18\x01 \x01(\t2\xbc\x02\n\nMatchmaker\x12+\n\x07newGame\x12\x0f.NewGameRequest\x1a\r.NewGameReply\"\x00\x12\x30\n\x08listGame\x12\x10.ListGameRequest\x1a\x0e.ListGameReply\"\x00\x30\x01\x12\x30\n\x08\x66indGame\x12\x10.FindGameRequest\x1a\x0e.FindGameReply\"\x00\x30\x01\x12\x34\n\ndeleteGame\x12\x12.DeleteGameRequest\x1a\x10.DeleteGameReply\"\x00\x12.\n\x08saveGame\x12\x10.SaveGameRequest\x1a\x0e.SaveGameReply\"\x00\x12\x37\n\x0blistPlayers\x12\x12.ListPlayerRequest\x1a\x10.ListPlayerReply\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'matchmaker_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NEWGAMEREQUEST._serialized_start=20
  _NEWGAMEREQUEST._serialized_end=70
  _NEWGAMEREPLY._serialized_start=72
  _NEWGAMEREPLY._serialized_end=103
  _LISTGAMEREQUEST._serialized_start=105
  _LISTGAMEREQUEST._serialized_end=122
  _LISTGAMEREPLY._serialized_start=124
  _LISTGAMEREPLY._serialized_end=190
  _FINDGAMEREQUEST._serialized_start=192
  _FINDGAMEREQUEST._serialized_end=243
  _FINDGAMEREPLY._serialized_start=245
  _FINDGAMEREPLY._serialized_end=311
  _DELETEGAMEREQUEST._serialized_start=313
  _DELETEGAMEREQUEST._serialized_end=366
  _DELETEGAMEREPLY._serialized_start=368
  _DELETEGAMEREPLY._serialized_end=402
  _SAVEGAMEREQUEST._serialized_start=404
  _SAVEGAMEREQUEST._serialized_end=421
  _SAVEGAMEREPLY._serialized_start=423
  _SAVEGAMEREPLY._serialized_end=455
  _LISTPLAYERREQUEST._serialized_start=457
  _LISTPLAYERREQUEST._serialized_end=492
  _LISTPLAYERREPLY._serialized_start=494
  _LISTPLAYERREPLY._serialized_end=531
  _MATCHMAKER._serialized_start=534
  _MATCHMAKER._serialized_end=850
# @@protoc_insertion_point(module_scope)
