# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import clientController_pb2 as clientController__pb2


class ClientControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendPing = channel.unary_unary(
                '/grpc.ClientController/SendPing',
                request_serializer=clientController__pb2.Ping.SerializeToString,
                response_deserializer=clientController__pb2.Pong.FromString,
                )
        self.SendAction = channel.unary_unary(
                '/grpc.ClientController/SendAction',
                request_serializer=clientController__pb2.Action.SerializeToString,
                response_deserializer=clientController__pb2.Empty.FromString,
                )
        self.ActionStream = channel.unary_stream(
                '/grpc.ClientController/ActionStream',
                request_serializer=clientController__pb2.Empty.SerializeToString,
                response_deserializer=clientController__pb2.Action.FromString,
                )
        self.FinishStream = channel.unary_stream(
                '/grpc.ClientController/FinishStream',
                request_serializer=clientController__pb2.Empty.SerializeToString,
                response_deserializer=clientController__pb2.EndNote.FromString,
                )


class ClientControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendPing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActionStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinishStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendPing': grpc.unary_unary_rpc_method_handler(
                    servicer.SendPing,
                    request_deserializer=clientController__pb2.Ping.FromString,
                    response_serializer=clientController__pb2.Pong.SerializeToString,
            ),
            'SendAction': grpc.unary_unary_rpc_method_handler(
                    servicer.SendAction,
                    request_deserializer=clientController__pb2.Action.FromString,
                    response_serializer=clientController__pb2.Empty.SerializeToString,
            ),
            'ActionStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ActionStream,
                    request_deserializer=clientController__pb2.Empty.FromString,
                    response_serializer=clientController__pb2.Action.SerializeToString,
            ),
            'FinishStream': grpc.unary_stream_rpc_method_handler(
                    servicer.FinishStream,
                    request_deserializer=clientController__pb2.Empty.FromString,
                    response_serializer=clientController__pb2.EndNote.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.ClientController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ClientController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendPing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.ClientController/SendPing',
            clientController__pb2.Ping.SerializeToString,
            clientController__pb2.Pong.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.ClientController/SendAction',
            clientController__pb2.Action.SerializeToString,
            clientController__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ActionStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpc.ClientController/ActionStream',
            clientController__pb2.Empty.SerializeToString,
            clientController__pb2.Action.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FinishStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpc.ClientController/FinishStream',
            clientController__pb2.Empty.SerializeToString,
            clientController__pb2.EndNote.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
